In [12]:
import pandas as pd

In [13]:
output_path = "../f0_OSMOSYS_ECU_Output.csv"
#output_path = "../docs/PLANMICCOutput.csv"
current = pd.read_csv(output_path)
current

C:\Users\adria\AppData\Local\Temp\ipykernel_13676\814693311.py:3: DtypeWarning: Columns (2,4,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  current = pd.read_csv(output_path)

,Strategy,Future.ID,Fuel,Technology,Emission,Year,Demand,NewCapacity,AccumulatedNewCapacity,TotalCapacityAnnual,...,Capex2023,FixedOpex2023,VarOpex2023,Opex2023,Externalities2023,Capex_GDP,FixedOpex_GDP,VarOpex_GDP,Opex_GDP,Externalities_GDP
0,BAU,0,DEMTRNFREHEA,TRNFREHEA,NaN,2010,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DDP,0,DEMTRNFREHEA,TRNFREHEA,NaN,2010,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BAU,0,DEMTRNFREHEA,TRNFREHEA,NaN,2011,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DDP,0,DEMTRNFREHEA,TRNFREHEA,NaN,2011,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BAU,0,DEMTRNFREHEA,TRNFREHEA,NaN,2012,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104015,DDP,0,NaN,TRNTAXLPG,NaN,2068,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104016,BAU,0,NaN,TRNTAXLPG,NaN,2069,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104017,DDP,0,NaN,TRNTAXLPG,NaN,2069,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104018,BAU,0,NaN,TRNTAXLPG,NaN,2070,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104019,DDP,0,NaN,TRNTAXLPG,NaN,2070,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
calibration_data_path = "calibration_data.csv"
calibration_df = pd.read_csv(calibration_data_path)
calibration_df

   Activity SubCategory  Year  TotalEmission
0        1A         1A1  2010        8049.22
1        1A         1A1  2012        7162.57
2        1A         1A1  2014        8568.71
3        1A         1A1  2016        7593.28
4        1A         1A1  2018        5733.76
5        1A         1A1  2020        4405.03
6        1A         1A1  2021        4403.42
7        1A         1A1  2022        5637.34
8        1A         1A2  2010        3201.83
9        1A         1A2  2012        3627.65
10       1A         1A2  2014        4316.55
11       1A         1A2  2016        3021.61
12       1A         1A2  2018        3224.96
13       1A         1A2  2020        2785.94
14       1A         1A2  2021        3013.69
15       1A         1A2  2022        3613.91
16       1A         1A3  2010       13244.08
17       1A         1A3  2012       14787.85
18       1A         1A3  2014       16926.04
19       1A         1A3  2016       18432.45
20       1A         1A3  2018       19834.19
21       1A         1A3  2020       16319.70
22       1A         1A3  2021       20144.68
23       1A         1A3  2022       21182.07
24       1A         1A4  2010        3042.80
25       1A         1A4  2012        3317.68
26       1A         1A4  2014        3605.28
27       1A         1A4  2016        3257.78
28       1A         1A4  2018        3438.45
29       1A         1A4  2020        3479.76
30       1A         1A4  2021        3602.30
31       1A         1A4  2022        3794.57
32       1A         1A5  2010        2912.24
33       1A         1A5  2012        3224.24
34       1A         1A5  2014        2933.17
35       1A         1A5  2016        2335.28
36       1A         1A5  2018        3127.37
37       1A         1A5  2020        2643.90
38       1A         1A5  2021        2024.47
39       1A         1A5  2022        2535.79
40       1B         1B2  2010        3679.79
41       1B         1B2  2012        3840.11
42       1B         1B2  2014        4226.75
43       1B         1B2  2016        4194.38
44       1B         1B2  2018        3943.65
45       1B         1B2  2020        3643.56
46       1B         1B2  2021        3603.23
47       1B         1B2  2022        3662.07

In [15]:
# Years
calibration_years = list(calibration_df['Year'].unique())

In [16]:
model_filters = (current['Year'].isin(calibration_years))&(current['Strategy'] == 'BAU') & (current['Emission'] == 'CO2') & (~current['AnnualTechnologyEmission'].isna())
model_df = current.loc[model_filters, ['Year', 'Technology', 'AnnualTechnologyEmission']]
model_df

       Year      Technology  AnnualTechnologyEmission
61826  2010    PPICRUPETICE                  2.071740
61830  2012    PPICRUPETICE                  2.008820
61834  2014    PPICRUPETICE                  2.406830
61838  2016    PPICRUPETICE                  2.117340
61842  2018    PPICRUPETICE                  1.299230
...     ...             ...                       ...
93538  2016  T5PURGSLSHITRN                  0.001454
93542  2018  T5PURGSLSHITRN                  0.002140
93546  2020  T5PURGSLSHITRN                  0.000687
93548  2021  T5PURGSLSHITRN                  0.001373
93550  2022  T5PURGSLSHITRN                  0.001391

[443 rows x 3 columns]

In [17]:
# Calibration 1A1
techs = {
    "1A1": [
"PP_NGSTGS",
"PPINGSPETTST",
"PPINGSPETICE",
"PPINGSPETTGS",
"PP_DSLICE",
"PP_DSLTGS",
"PPIDSLGALICE",
"PPIDSLELRICE",
"PPIDSLELRTST",
"PPIDSLCEMTST",
"PPIDSLPETTGS",
"PPIDSLPETICE",
"PPIFOIPETICE",
"PP_FOIICE",
"PP_FOITST",
"PP_TPP",
"PROCRU",
"REFCRU",
"REFCRUDSL",
"REFCRUGSL",
"REFCRULPG",
"REFCRUFOI",
"REFCRUKJF",
"REFCRUCOK",
"REFCRURED",
"REFNONENE",
"RSVCRU",
"PP_CRU",
"PPICRUPETICE",
"PPICRUPETTST",

    ],
    "1A2": [
        "T5FOIIND",
        "T5LPGIND",
        "T5NGSIND",
        "T5PURDSLIND",
        "T5PURGSLIND",
        "T5COKIND",

    ],
    "1A3": [

        "T4_DSLPUB",
        "T4_GSLPUB",
        "T4_LPGPUB",
        "T4_NGSPUB",
        "T4_DSLPRI",
        "T4_GSLPRI",
        "T4_LPGPRI",
        "T4_NGSPRI",
        "T4_DSLHEA",
        "T4_GSLHEA",
        "T4_LPGHEA",
        "T4_NGSMED",
        "T4_DSLMED",
        "T4_GSLMED",
        "T4_LPGMED",
        "T4_DSLLIG",
        "T4_GSLLIG",
        "T4_LPGLIG",
        "T4_NGSLIG",
        "TRNMIC",
        "TRNBUS",
        "TRNTAX",
        "TRNPASRAI",
        "TRNMOT",
        "TRNSED",
        "TRNSUV",
        "TRNCAM",
        "TRNFREHEA",
        "TRNFREMED",
        "TRNFRELIG",
        "TRNCATTRU",
        "TRNFRERAI",
        "T5KJFAERTRN",
        "T5FOISHITRN",
        "T5PURDSLSHITRN",
        "T5PURGSLSHITRN",

    ],
    "1A4": [
        "T5FOICOM",
        "T5LPGCOM",
        "T5PURGSLCOM",
        "T5PURDSLCOM",
        "T5LPGRES",
        "T5NGSRES",
        "T5LPGAGR",
        "T5PURGSLAGR",
        "T5NOEAGR",
        "T5LPGCON",
        "T5PURGSLCON",
        "T5PURDSLCON",

    ],
    # "1A5": [

    # ]
    "1B2":[
        "T5CRUCRUTRN"
    ]
}

def check_calibration(sub_category:str):
    # Model Results
    model_filters = (model_df['Technology'].isin(techs[sub_category]))
    model_output = model_df.loc[model_filters, ['Year', 'Technology', 'AnnualTechnologyEmission']]
    model = model_output.groupby('Year')[['AnnualTechnologyEmission']].agg('sum').reset_index()
    model['AnnualTechnologyEmission'] = model["AnnualTechnologyEmission"] * 1000 # Mt to Gg
    model = model.rename(columns={"AnnualTechnologyEmission":"Model"})

    # check if all specified techs are found in the model
    model_techs = list(model_output['Technology'].unique())
    if len(model_techs) != len(techs[sub_category]):
        missing_techs = list(set(techs[sub_category]) - set(model_techs))
        print("WARNING: The following techs are missing in the model.")
        print(missing_techs)


    # Calibration Results
    calib = calibration_df.loc[calibration_df['SubCategory']==sub_category, ['Year', 'TotalEmission']]
    calib = calib.rename(columns={"TotalEmission":"INGEI"})

    result = pd.merge(model, calib, on='Year', how='inner')
    result['Error'] = (result['Model'] - result['INGEI'])/ result['INGEI'] * 100
    print(result)

In [18]:
print("*** Industrias de la energía (1A1) ***")
check_calibration("1A1")

*** Industrias de la energía (1A1) ***
WARNING: The following techs are missing in the model.
['REFCRUGSL', 'PPIDSLELRTST', 'REFCRURED', 'REFCRULPG', 'REFCRUCOK', 'REFCRUKJF', 'REFNONENE', 'PPIFOIPETICE', 'PP_TPP', 'PPIDSLCEMTST', 'PP_CRU', 'REFCRUFOI', 'RSVCRU', 'REFCRUDSL', 'PROCRU']
   Year       Model    INGEI      Error
0  2010  8123.22090  8049.22   0.919355
1  2012  8852.31918  7162.57  23.591381
2  2014  9614.52920  8568.71  12.205095
3  2016  9165.57040  7593.28  20.706340
4  2018  7260.48036  5733.76  26.626862
5  2020  5836.74885  4405.03  32.501909
6  2021  5809.53079  4403.42  31.932243
7  2022  6420.01040  5637.34  13.883683

In [19]:
print("*** Industrias manufactureras y de la construcción (1A2) ***")
check_calibration("1A2")

*** Industrias manufactureras y de la construcción (1A2) ***
WARNING: The following techs are missing in the model.
['T5COKIND']
   Year      Model    INGEI     Error
0  2010  3161.5430  3201.83 -1.258249
1  2012  3441.4708  3627.65 -5.132226
2  2014  4052.5482  4316.55 -6.116037
3  2016  2773.7842  3021.61 -8.201780
4  2018  3040.8167  3224.96 -5.709941
5  2020  2658.3139  2785.94 -4.581079
6  2021  2793.7429  3013.69 -7.298266
7  2022  3392.8901  3613.91 -6.115811

In [20]:
print("*** Transporte (1A3) ***")
check_calibration("1A3")

*** Transporte (1A3) ***
WARNING: The following techs are missing in the model.
['TRNFREMED', 'T4_LPGPRI', 'TRNFRERAI', 'T4_LPGHEA', 'T4_NGSLIG', 'TRNFREHEA', 'TRNFRELIG', 'T4_LPGMED', 'TRNMOT', 'T4_LPGLIG', 'TRNSUV', 'TRNCATTRU', 'TRNMIC', 'TRNTAX', 'TRNBUS', 'TRNCAM', 'TRNPASRAI', 'T4_GSLHEA', 'T4_GSLMED', 'T4_NGSPRI', 'T4_LPGPUB', 'TRNSED']
   Year         Model     INGEI      Error
0  2010  18809.246023  13244.08  42.020027
1  2012  18810.815390  14787.85  27.204532
2  2014  18883.659130  16926.04  11.565724
3  2016  19157.588650  18432.45   3.934033
4  2018  19158.120380  19834.19  -3.408607
5  2020  17688.924838  16319.70   8.390012
6  2021  18725.922380  20144.68  -7.042840
7  2022  18786.443000  21182.07 -11.309693

In [21]:
print("*** Otros sectores (1A4) ***")
check_calibration("1A4")

*** Otros sectores (1A4) ***
WARNING: The following techs are missing in the model.
['T5NOEAGR']
   Year        Model    INGEI      Error
0  2010  5009.074800  3042.80  64.620573
1  2012  5626.210500  3317.68  69.582675
2  2014  6300.031337  3605.28  74.744578
3  2016  5470.881860  3257.78  67.932821
4  2018  6341.521980  3438.45  84.429670
5  2020  5709.994300  3479.76  64.091613
6  2021  5680.506160  3602.30  57.691091
7  2022  5991.525340  3794.57  57.897346

In [22]:
print("*** Petróleo y Gas Natural (1B2) ***")
check_calibration("1B2")

*** Petróleo y Gas Natural (1B2) ***
   Year    Model    INGEI      Error
0  2010  447.347  3679.79 -87.843138
1  2012  447.347  3840.11 -88.350672
2  2014  447.347  4226.75 -89.416289
3  2016  447.347  4194.38 -89.334610
4  2018  447.347  3943.65 -88.656524
5  2020  455.052  3643.56 -87.510786
6  2021  437.929  3603.23 -87.846210
7  2022  456.551  3662.07 -87.532980